### ISSUE TITLE
Upgrade Cairo0-ERC-4906 to Cairo 2.6

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-4906#1]
**Description**
---
Upgrade the implementation of ERC-4906 to Cairo 2.6 from the [Cairo0 repo](https://github.com/Carbonable-labs/cairo0-erc-4906) using Starknet components.

**Additional Information**
---------------------------
[Medium Difficult  - Cairo - high Priority]

**Acceptance Criteria**
---

- [ ] Implementation of a component-based ERC-4906

**Comment by TAdev0** [comment]
Hey @tekkac  @Khyati729 , may i be assigned to this issue? 
Thank you!

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue
