### ISSUE TITLE
Update unit testing

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-4906#2]
**Description**
---
Upgrade the implementation of ERC-4906 to Cairo 2.6 from the [Cairo0 repo](https://github.com/Carbonable-labs/cairo0-erc-4906) using Starknet components.

**Additional Information**
---------------------------
[Easy  - Cairo - medium Priority]

**Acceptance Criteria**
---

- [ ] Implementation of a component-based ERC-4906

**Comment by ArnaudBD** [comment]
Can I do this one?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by TAdev0** [comment]
@ArnaudBD  hi, how you started yet? You can check my last curent PR code, which might be a good start to implement unit tests.

**Comment by aagbotemi** [comment]
@Khyati729 @TAdev0. I will love to take this issue, if it is still available.

**Comment by stevencartavia** [comment]
Hi, is this issue still unresolved?

**Comment by EmmanuelAR** [comment]
Hey @tekkac ,

I hope you're doing well! I'm Emmanuel, a software developer from Costa Rica. I've participated in past ODHack editions and really enjoyed them.

Just wanted to check if the issue you mentioned is still available. I'm interested in working on it and would love to get more details.

Thanks a lot!

Best,
Emmanuel
