### ISSUE TITLE
Update e2e tests

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/cairo-erc-4906#3]
**Description**
---
Adapt and implement end-to-end tests using Starknet Foundry in Cairo 2.6 from the [Cairo0 repo](https://github.com/Carbonable-labs/cairo0-erc-4906).

**Additional Information**
---------------------------
[Easy  - Cairo - Low Priority]

**Acceptance Criteria**
---
- [ ] Add the Starknet Foundry dependency
- [ ] Adapt and pass e2e tests.

**Comment by JimmyFate** [comment]
I can take this :)

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by Joy-Adah** [comment]
Hi @Khyati729 I'd love to work on this

**Comment by 0xthomass** [comment]
Hey, may I take this one ?

**Comment by TAdev0** [comment]
@thomas192  hi, how you started yet? You can check my last curent PR code, which might be a good start to implement integration tests!

**Comment by 0xthomass** [comment]
> @thomas192 hi, how you started yet? You can check my last curent PR code, which might be a good start to implement integration tests!

Hey, thanks for the message I was able to get started yesterday using your PR :)

**Comment by thomas192** [comment]
Hey @tekkac I have a question please see draft PR #6

**Comment by 0xthomass** [comment]
Hello @tekkac I have a question please see draft PR #6
